#!/usr/bin/env bash
# Write dogecoin.conf + RPC-CREDENTIALS.txt (fresh install only unless --force).
# UTF-8 plain text; never a shared default password.
set -euo pipefail

DATA_DIR=""
RPC_PASS=""
RPC_USER="dogecoin"
PROFILE="core"
EXAMPLE=""
FORCE=0

usage() {
  echo "Usage: $0 --datadir DIR --rpcpassword PASS [--rpcuser USER] [--profile dump|settlement|core|hybrid] [--example FILE] [--force]"
  exit 2
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --datadir) DATA_DIR="$2"; shift 2 ;;
    --rpcpassword) RPC_PASS="$2"; shift 2 ;;
    --rpcuser) RPC_USER="$2"; shift 2 ;;
    --profile) PROFILE="$2"; shift 2 ;;
    --example) EXAMPLE="$2"; shift 2 ;;
    --force) FORCE=1; shift ;;
    -h|--help) usage ;;
    *) echo "unknown arg: $1"; usage ;;
  esac
done

[[ -n "$DATA_DIR" && -n "$RPC_PASS" ]] || usage

mkdir -p "$DATA_DIR"
CONF="${DATA_DIR}/dogecoin.conf"
CRED="${DATA_DIR}/RPC-CREDENTIALS.txt"
UTC="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

if [[ -f "$CONF" && "$FORCE" -ne 1 ]]; then
  echo "CONF_EXISTS $CONF"
  exit 0
fi

case "$PROFILE" in
  dump)
    EXTRA=$'prune=5500\ndbcache=1024\nmaxmempool=50\nmaxconnections=32\ndisablewallet=1\nprinttoconsole=0\ntxindex=0\n'
    ;;
  settlement)
    EXTRA=$'prune=0\ndbcache=2048\nmaxmempool=100\nmaxconnections=40\ndisablewallet=0\nprinttoconsole=0\ntxindex=0\n'
    ;;
  hybrid)
    EXTRA=$'# Hybrid: ImGui + operator TUI share THIS one node.\nprune=5500\ndbcache=1024\nmaxmempool=50\nmaxconnections=40\ndisablewallet=0\nprinttoconsole=0\ntxindex=0\n'
    ;;
  *)
    EXTRA=$'# Core GUI / Client\nprinttoconsole=0\n'
    ;;
esac

if [[ -n "$EXAMPLE" && -f "$EXAMPLE" && "$PROFILE" != "core" ]]; then
  {
    echo "# Generated by installer - unique credentials for THIS install only."
    echo "# Created: $UTC"
    while IFS= read -r line || [[ -n "$line" ]]; do
      line="${line#$'\xEF\xBB\xBF'}"
      if [[ "$line" =~ ^[[:space:]]*rpcuser[[:space:]]*= ]]; then
        echo "rpcuser=${RPC_USER}"
        continue
      fi
      if [[ "$line" =~ ^[[:space:]]*rpcpassword[[:space:]]*= ]]; then
        echo "rpcpassword=${RPC_PASS}"
        continue
      fi
      if [[ "$line" =~ CHANGE_ME|REPLACE_WITH_UNIQUE ]]; then
        continue
      fi
      echo "$line"
    done < "$EXAMPLE"
  } > "$CONF"
else
  cat > "$CONF" <<EOF
# Generated by installer - unique credentials for THIS install only.
# Created: $UTC
# Profile: $PROFILE

server=1
listen=1

rpcbind=127.0.0.1
rpcallowip=127.0.0.1
rpcuser=${RPC_USER}
rpcpassword=${RPC_PASS}

${EXTRA}
EOF
fi

cat > "$CRED" <<EOF
Dogecoin RPC credentials - THIS INSTALL ONLY
============================================
Generated: $UTC
Data dir:  $DATA_DIR
Conf file: $CONF

rpcuser=${RPC_USER}
rpcpassword=${RPC_PASS}

RPC is bound to 127.0.0.1 by default.
Store this securely. You can delete this file after saving the password elsewhere.
Do not share this file. Do not commit it to git.
EOF

chmod 640 "$CONF" "$CRED" 2>/dev/null || true
echo "CONF_OK $CONF"
echo "CRED_OK $CRED"
