# Write dogecoin.conf + RPC-CREDENTIALS.txt for a fresh install.
# Never uses a shared default password.
# IMPORTANT: dogecoin.conf must be UTF-8 WITHOUT BOM (or ASCII). BOM breaks dogecoind.
param(
  [Parameter(Mandatory = $true)][string]$DataDir,
  [Parameter(Mandatory = $true)][string]$RpcPassword,
  [string]$RpcUser = "gpenode",
  [ValidateSet("dump", "settlement", "core", "hybrid")]
  [string]$Profile = "dump",
  [string]$ExampleConf = "",
  [ValidateSet("leveldb", "mdbx")]
  [string]$DbEngine = "leveldb",
  [switch]$Force
)
$ErrorActionPreference = "Stop"

function Write-Utf8NoBom([string]$Path, [string]$Text) {
  $enc = New-Object System.Text.UTF8Encoding $false
  [System.IO.File]::WriteAllText($Path, $Text, $enc)
}

function Write-InstallLog([string]$DataDir, [string]$Msg) {
  try {
    $logDir = Join-Path $DataDir "logs"
    New-Item -ItemType Directory -Force -Path $logDir | Out-Null
    $log = Join-Path $logDir ("install-{0}.log" -f (Get-Date -Format "yyyyMMdd"))
    $line = "{0} Z {1}" -f (Get-Date).ToUniversalTime().ToString("o"), $Msg
    Add-Content -Path $log -Value $line -Encoding ASCII
  } catch { }
}

New-Item -ItemType Directory -Force -Path $DataDir | Out-Null
$conf = Join-Path $DataDir "dogecoin.conf"
$cred = Join-Path $DataDir "RPC-CREDENTIALS.txt"
$utc = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")

if ((Test-Path $conf) -and -not $Force) {
  Write-Host "CONF_EXISTS $conf"
  Write-InstallLog $DataDir "CONF_EXISTS $conf"
  exit 0
}

try {
  if ($ExampleConf -and (Test-Path $ExampleConf) -and $Profile -ne "core") {
    $lines = Get-Content $ExampleConf -Encoding UTF8
    $out = New-Object System.Collections.Generic.List[string]
    [void]$out.Add("# Generated by installer - unique credentials for THIS install only.")
    [void]$out.Add("# Created: $utc")
    $seenUser = $false
    $seenPass = $false
    foreach ($line in $lines) {
      # strip BOM if present on first line
      if ($line.Length -gt 0 -and [int][char]$line[0] -eq 0xFEFF) {
        $line = $line.Substring(1)
      }
      if ($line -match '^\s*rpcuser\s*=') {
        [void]$out.Add("rpcuser=$RpcUser")
        $seenUser = $true
        continue
      }
      if ($line -match '^\s*rpcpassword\s*=') {
        [void]$out.Add("rpcpassword=$RpcPassword")
        $seenPass = $true
        continue
      }
      if ($line -match 'CHANGE_ME|REPLACE_WITH_UNIQUE') { continue }
      [void]$out.Add($line)
    }
    if (-not $seenUser) { [void]$out.Add("rpcuser=$RpcUser") }
    if (-not $seenPass) { [void]$out.Add("rpcpassword=$RpcPassword") }
    $body = ($out -join "`n") + "`n"
  } else {
    $extra = switch ($Profile) {
      "dump" {
        @(
          "prune=5500"
          "dbcache=1024"
          "maxmempool=50"
          "maxconnections=32"
          "disablewallet=1"
          "printtoconsole=0"
          "txindex=0"
        ) -join "`n"
      }
      "settlement" {
        @(
          "prune=0"
          "dbcache=2048"
          "maxmempool=100"
          "maxconnections=40"
          "disablewallet=0"
          "printtoconsole=0"
          "txindex=0"
        ) -join "`n"
      }
      "hybrid" {
        @(
          "# Hybrid: ImGui + operator TUI share THIS one node."
          "prune=5500"
          "dbcache=1024"
          "maxmempool=50"
          "maxconnections=40"
          "disablewallet=0"
          "printtoconsole=0"
          "txindex=0"
        ) -join "`n"
      }
      default {
        "# Core GUI / general node`nprinttoconsole=0"
      }
    }
    $body = @"
# Generated by installer - unique credentials for THIS install only.
# Created: $utc
# Profile: $Profile

server=1
listen=1

rpcbind=127.0.0.1
rpcallowip=127.0.0.1
rpcuser=$RpcUser
rpcpassword=$RpcPassword
dbengine=$DbEngine

$extra
"@
  }

  Write-Utf8NoBom $conf $body

  $credBody = @"
Dogecoin RPC credentials - THIS INSTALL ONLY
============================================
Generated: $utc
Data dir:  $DataDir
Conf file: $conf

rpcuser=$RpcUser
rpcpassword=$RpcPassword

RPC is bound to 127.0.0.1 by default.
Store this securely. You can delete this file after saving the password elsewhere.
Do not share this file. Do not commit it to git.
"@
  Write-Utf8NoBom $cred $credBody

  Write-Host "CONF_OK $conf"
  Write-Host "CRED_OK $cred"
  Write-InstallLog $DataDir "CONF_OK $conf CRED_OK $cred"
  exit 0
} catch {
  Write-Host "CONF_FAIL $($_.Exception.Message)"
  Write-InstallLog $DataDir "CONF_FAIL $($_.Exception.Message)"
  exit 1
}
